learning_templates/basic_app/urls.py
from django.urls import path
from basic_app import views

#TEMPLATE TAGGING
app_name = 'basic_app'

urlpatterns = [

path('relative/', views.relative , name = 'relative'),
path('other/', views.other , name = 'other'),

]

learning_templates/learning_templates/urls.py
from django.contrib import admin
from django.urls import path,include

from basic_app import views
urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.index , name = 'index'),
    path('basic_app/', include('basic_app.urls')),
]

learning_templates/basic_app/models.py
from django.db import models

# Create your models here.

learning_templates/basic_app/views.py
from django.shortcuts import render

# Create your views here.
def index(request):
    context_dict = {'text': 'hello world' , 'number': 100}
    return render(request,'basic_app/index.html',context_dict)

def other(request):
    return render(request,'basic_app/other.html')

def relative(request):
    return render(request,'basic_app/relatives_urls_templates.html')        

learning_templates/templates/basic_app/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0-alpha1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-GLhlTQ8iRABdZLl6O3oVMWSktQOp6b7In1Zl3/Jr59b6EGGoI1aFkw7cmDA6j6gD" crossorigin="anonymous">

</head>
<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <div class ="container">
            <ul class ="nav navbar-nav">
                <li ><a class="navbar-brand" href="{% url 'index' %}">BRAND</a></li>
                <li ><a class="nav-link" href="{% url 'admin:index' %}">Admin</a></li>
                <li ><a class="nav-link" href="{% url 'basic_app:other' %}">Other</a></li>

            </ul>

        </div>

    </nav>
    <div class ="container">
        {% block body_block %}
        <!--anything outside of this will be inherited -->
        {% endblock %}

    </div>
</body>
</html>

learning_templates/templates/basic_app/index.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>WELCOME TO INDEX</h1>
    <h2>This is index.html page showing</h2>
    <h1>{{ text|cut:'hello' }}</h1>
    <h1>{{ number|add:'99' }}</h1>
    
    
    {% endblock %}

learning_templates/templates/basic_app/other.html
<!DOCTYPE html>
{% extends "basic_app/base.html" %}
{% block body_block %}
    <h1>WELCOME TO OTHER</h1>
    <h2>This is an example of template inheritance</h2>
    {% endblock %}

learning_templates/templates/basic_app/relatives_urls_templates.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <h1>WELCOME TO RELATIVE URLS TEMPLATES</h1>
    <a href="{% url 'basic_app:other' %}"> The other page</a>
    <a href="{% url 'admin:index' %}"> admin </a>
    <a href="{% url 'index' %}">index</a>
</body>
</html>